#!/bin/sh

# add more args here according to preference
ARGS="--volume=60"

notification(){
# change the icon to whatever you want. Make sure your notification server 
# supports it and already configured.

# Now it will receive argument so the user can rename the radio title
# to whatever they want

	notify-send "Playing now: " "$@" --icon=media-tape
}

menu(){
	printf "1. Lofi Girl\n"
	printf "2. Chillhop\n"
	printf "3. Box Lofi\n"
	printf "4. 538 Dance Dept\n"
	printf "5. Slam! MixMarathon\n"
	printf "6. Slam! The Boom Room\n"
}

main() {
	choice=$(menu | rofi -dmenu | cut -d. -f1)

	case $choice in
		1)
			notification "Lofi Girl ☕️🎶";
            URL="https://play.streamafrica.net/lofiradio"
			break
			;;
		2)
			notification "Chillhop ☕️🎶";
            URL="http://stream.zeno.fm/fyn8eh3h5f8uv"
			break
			;;
		3)
			notification "Box Lofi ☕️🎶";
            URL="http://stream.zeno.fm/f3wvbbqmdg8uv"
			break
			;;
		4)
			notification "538 Dance Dept ☕️🎶";
            URL="http://playerservices.streamtheworld.com/api/livestream-redirect/TLPSTR01.mp3"
			break
			;;
		5)
			notification "Slam! MixMarathon ☕️🎶";
            URL="https://stream.slam.nl/web13_mp3"
			break
			;;
		6)
			notification "The Boom Room ☕️🎶";
            URL="https://stream.slam.nl/web12_mp3"
			break
			;;
	esac
    # run mpv with args and selected url
    # added title arg to make sure the pkill command kills only this instance of mpv
    mpv $ARGS --title="radio-mpv" $URL
}

pkill -f radio-mpv || main
