## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░
## CROSS-SHELL PROMPT
##
## rxyhn's starship configuration
## The minimal, blazing-fast, and infinitely customizable prompt for any shell!

format = "$all"
right_format = """$git_branch$git_status$cmd_duration$directory"""

# Disable the blank line at the start of the prompt
add_newline = false

[line_break]
disabled = true

[character]
success_symbol = " [](#7CB6F5)[](#eed49f)[](#ed8796)"
error_symbol = " [](#ed8796)"
vicmd_symbol = "[  ](#A6D189)"

[hostname]
ssh_only = true
format = "[$hostname](bold blue) "
disabled = false

[cmd_duration]
min_time = 1
format = "[](fg:#2E3440 bg:none)[$duration]($style)[](fg:#2E3440 bg:#2E3440)[](fg:#c6a0f6 bg:#2E3440)[](fg:#2E3440 bg:#c6a0f6)[](fg:#c6a0f6 bg:none) "
disabled = false
style = "fg:#edeff0 bg:#2E3440"

[directory]
format = "[](fg:#2E3440 bg:none)[$path]($style)[](fg:#2E3440 bg:#2E3440)[](fg:#7CB6F5 bg:#2E3440)[](fg:#2E3440 bg:#7CB6F5)[](fg:#7CB6F5 bg:none)"
style = "fg:#edeff0 bg:#2E3440"
truncation_length = 3
truncate_to_repo=false

[git_branch]
format = "[](fg:#2E3440 bg:none)[$branch]($style)[](fg:#2E3440 bg:#2E3440)[](fg:#A6D189 bg:#2E3440)[](fg:#282c34 bg:#A6D189)[](fg:#A6D189 bg:none) "
style = "fg:#edeff0 bg:#2E3440"

[git_status]
format="[](fg:#2E3440 bg:none)[$all_status$ahead_behind]($style)[](fg:#2E3440 bg:#2E3440)[](fg:#94E2D5 bg:#2E3440)[](fg:#2E3440 bg:#94E2D5)[](fg:#94E2D5 bg:none) "
style = "fg:#edeff0 bg:#2E3440"
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "${count}"

[git_commit]
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"
style = "green"

[git_state]
rebase = "REBASING"
merge =	"MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style =	"yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\) '
